In [2]:
import pandas as pd
import numpy as np

In [3]:
customer_df=pd.read_csv("customers.csv")
order_df=pd.read_csv("orders.csv")
product_df=pd.read_csv("products.csv")

In [4]:
print(customer_df.shape)
print(order_df.shape)
print(product_df.shape)

(20, 7)
(100, 10)
(10, 6)

In [5]:
customer_df.isnull().sum()

CustomerID      0
CustomerName    0
Segment         0
Gender          0
Age             0
City            0
Country         0
dtype: int64

In [6]:
order_df.isnull().sum()

OrderID        0
OrderDate      0
CustomerID     0
ProductID      0
Quantity       0
Sales          0
Discount       0
Profit         0
Region         0
PaymentMode    0
dtype: int64

In [7]:
product_df.isnull().sum()

ProductID      0
ProductName    0
Category       0
SubCategory    0
Cost           0
Supplier       0
dtype: int64

In [8]:
customer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    20 non-null     object
 1   CustomerName  20 non-null     object
 2   Segment       20 non-null     object
 3   Gender        20 non-null     object
 4   Age           20 non-null     int64
 5   City          20 non-null     object
 6   Country       20 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.2+ KB

In [9]:
order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      100 non-null    object
 1   OrderDate    100 non-null    object
 2   CustomerID   100 non-null    object
 3   ProductID    100 non-null    object
 4   Quantity     100 non-null    int64
 5   Sales        100 non-null    int64
 6   Discount     100 non-null    float64
 7   Profit       100 non-null    int64
 8   Region       100 non-null    object
 9   PaymentMode  100 non-null    object
dtypes: float64(1), int64(3), object(6)
memory usage: 7.9+ KB

In [10]:
order_df["OrderDate"]=pd.to_datetime(order_df["OrderDate"])

In [11]:
order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      100 non-null    object
 1   OrderDate    100 non-null    datetime64[ns]
 2   CustomerID   100 non-null    object
 3   ProductID    100 non-null    object
 4   Quantity     100 non-null    int64
 5   Sales        100 non-null    int64
 6   Discount     100 non-null    float64
 7   Profit       100 non-null    int64
 8   Region       100 non-null    object
 9   PaymentMode  100 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(3), object(5)
memory usage: 7.9+ KB

In [12]:
customer_df.head()

  CustomerID  CustomerName      Segment  Gender  Age     City Country
0       C001   Rahul Menon    Corporate    Male   28   Mumbai   India
1       C002  Priya Sharma  Home Office  Female   34    Delhi   India
2       C003   John Dsouza     Consumer    Male   40    Kochi   India
3       C004     Meena Raj     Consumer  Female   29     Pune   India
4       C005   Vikram Iyer    Corporate    Male   31  Chennai   India

In [13]:
order_df.head()

,OrderID,OrderDate,CustomerID,ProductID,Quantity,Sales,Discount,Profit,Region,PaymentMode
0,O1001,2024-01-01,C001,P001,1,250,0.00,40,North,UPI
1,O1002,2024-01-02,C002,P002,2,400,0.05,80,South,Credit Card
2,O1003,2024-01-03,C003,P003,3,900,0.10,180,East,COD
3,O1004,2024-01-04,C004,P004,1,300,0.00,50,West,Net Banking
4,O1005,2024-01-05,C005,P005,2,500,0.20,100,Central,Debit Card

In [14]:
product_df.head()

  ProductID     ProductName    Category  SubCategory  Cost Supplier
0      P001     Laptop X210  Technology      Laptops   300       HP
1      P002      Desk Chair   Furniture       Chairs   150     Ikea
2      P003  Headphones Pro  Technology  Accessories   100     Sony
3      P004    Office Table   Furniture       Tables   250     Ikea
4      P005     LED Monitor  Technology     Monitors   200     Dell