In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df["Price"] = housing.target

In [4]:
display(df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  Price
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88    -122.23  4.526
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86    -122.22  3.585
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85    -122.24  3.521
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85    -122.25  3.413
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85    -122.25  3.422

In [5]:
X = df[["MedInc", "AveRooms","HouseAge","AveBedrms","Population","AveOccup","Latitude","Longitude"]]   # picking 2 features for simplicity
y = df["Price"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create model
model = LinearRegression()

# Train (fit)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

In [ ]:
# Evaluate
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)
print("MSE:", mean_squared_error(y_test, y_pred))
print("R^2 Score:", r2_score(y_test, y_pred))

Coefficients: [ 4.48674910e-01 -1.23323343e-01  9.72425752e-03  7.83144907e-01
 -2.02962058e-06 -3.52631849e-03 -4.19792487e-01 -4.33708065e-01]
Intercept: -37.023277706064114
MSE: 0.5558915986952413
R^2 Score: 0.5757877060324531

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   Price       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [9]:
df.describe()

             MedInc      HouseAge      AveRooms     AveBedrms  ...      AveOccup      Latitude     Longitude         Price
count  20640.000000  20640.000000  20640.000000  20640.000000  ...  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.870671     28.639486      5.429000      1.096675  ...      3.070655     35.631861   -119.569704      2.068558
std        1.899822     12.585558      2.474173      0.473911  ...     10.386050      2.135952      2.003532      1.153956
min        0.499900      1.000000      0.846154      0.333333  ...      0.692308     32.540000   -124.350000      0.149990
25%        2.563400     18.000000      4.440716      1.006079  ...      2.429741     33.930000   -121.800000      1.196000
50%        3.534800     29.000000      5.229129      1.048780  ...      2.818116     34.260000   -118.490000      1.797000
75%        4.743250     37.000000      6.052381      1.099526  ...      3.282261     37.710000   -118.010000      2.647250
max       15.000100     52.000000    141.909091     34.066667  ...   1243.333333     41.950000   -114.310000      5.000010

[8 rows x 9 columns]

In [10]:
display(df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  Price
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88    -122.23  4.526
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86    -122.22  3.585
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85    -122.24  3.521
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85    -122.25  3.413
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85    -122.25  3.422

In [11]:
df["HouseAge"]=df["HouseAge"].apply(int)
display(df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  Price
0  8.3252        41  6.984127   1.023810       322.0  2.555556     37.88    -122.23  4.526
1  8.3014        21  6.238137   0.971880      2401.0  2.109842     37.86    -122.22  3.585
2  7.2574        52  8.288136   1.073446       496.0  2.802260     37.85    -122.24  3.521
3  5.6431        52  5.817352   1.073059       558.0  2.547945     37.85    -122.25  3.413
4  3.8462        52  6.281853   1.081081       565.0  2.181467     37.85    -122.25  3.422

In [20]:
test_df=df.drop(0,axis=0)

In [21]:
display(test_df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  Longitude  Price
1  8.3014        21  6.238137   0.971880      2401.0  2.109842     37.86    -122.22  3.585
2  7.2574        52  8.288136   1.073446       496.0  2.802260     37.85    -122.24  3.521
3  5.6431        52  5.817352   1.073059       558.0  2.547945     37.85    -122.25  3.413
4  3.8462        52  6.281853   1.081081       565.0  2.181467     37.85    -122.25  3.422
5  4.0368        52  4.761658   1.103627       413.0  2.139896     37.85    -122.25  2.697